### ISSUE TITLE
Checking storage update of external contract

### ISSUE THREAD

**Issue by Leonard-Pat** [NethermindEth/horus-checker#173]
**Describe the bug**
Horus can't seem to check a storage update of an external function call. In my example Contract B calls the function 'initialize' in Contract A, which updates a storage variable (in contract A). If i write the horus condition in Contract B checking that a storage update was indeed made, then i get error:
```
ContractB.cairo:1:1: Unknown identifier '_storvar'.
@storage_update _storvar() := 1
^*****************************^ 
```
I was wondering if this behaviour is normal / would it be possible to add this feature, as I am testing mutliple contract interactions for a project!

Contract A:
```cairo
%lang starknet


from starkware.cairo.common.cairo_builtins import HashBuiltin, SignatureBuiltin, EcOpBuiltin


@storage_var
func _storvar() -> (res: felt) {
}


namespace LibraryContract {


    func initialize{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
        x: felt
    ) {
        // initialize the contract
        _storvar.write(x);
        return ();
    }

}
```

Contract B:
```cairo
%lang starknet


from starkware.cairo.common.cairo_builtins import HashBuiltin, SignatureBuiltin, EcOpBuiltin
from ContractA import (
LibraryContract
)


//@storage_update _storvar() := 1
@external
func main{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}() {
    LibraryContract.initialize(1);
    return ();
}
```

* Versions of SMT solvers used (`z3 --version`, `mathsat -version`, `cvc5 --version`).
* Z3 version 4.12.1 - 64 bit
* Horus version: 0.1.0.1
* Horus-compile (required): >=0.0.6.8, <0.0.7
* This is cvc5 version 1.0.3 [git tag 1.0.3 branch HEAD]
compiled with GCC version 11.3.0

**Operating system**
[ x] Linux
[ ] MacOS
[ ] Windows
[ ] Other (please write)

**CPU architecture**
[ x] x86-64
[ ] AArch64
[ ] Other (please write)

**Comment by langfield** [comment]
What is `x`? I suppose you mean the literal value `1`?

**Comment by langfield** [comment]
Yes, so there was a bit of confusion internally as a result of this example, but @Julek pointed out that these are not _technically_ different contracts, they are only different modules/files. Just a terminology hang-up.

That aside, the primary issue here is that you need to import `_starvar` in `ContractB.cairo` in order for Horus to see it.

After that, Horus will work. But then it will complain because there is no `@storage_update` annotation for `initialize()`.
