### ISSUE TITLE
Are `@storage_update` annotations supported in namespaces?

### ISSUE THREAD

**Issue by Leonard-Pat** [NethermindEth/horus-checker#174]
**Expected behavior**
In this example:

```cairo
%lang starknet


from starkware.cairo.common.cairo_builtins import HashBuiltin, SignatureBuiltin, EcOpBuiltin


@storage_var
func _storvar() -> (res: felt) {
}


namespace TestContract {

    //@storage_update _storvar() := x
    func initialize{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
        x: felt
    ) {
        // initialize the contract
        _storvar.write(x);
        return ();
    }

}
```

compiling / checking doesnt produce an output as the condition is written inside the namespace 'TestContract'. As of now it works if you remove the namespace or add an external function i.e. main, that calls the function TestContract.initialize. Would it be possible for horus to check functions inside a namespace without calling the function externally ?

**Operating system**
[ x] Linux
[ ] MacOS
[ ] Windows
[ ] Other (please write)

**CPU architecture**
[ x] x86-64
[ ] AArch64
[ ] Other (please write)

**Comment by langfield** [comment]
As mentioned in the other issue, we don't support `@storage_update` in namespaces yet! 😢  Sorry!
